### ISSUE TITLE
为什么我在训练时dice一直为0？

### ISSUE THREAD

**Issue by jscodecode** [Dootmaan/MT-UNet#13]
非常感谢你们很好的工作！但我有两个问题：
问题一：我使用的是冠脉数据集。
1）如果将同一组数据集既作为训练集，也作为测试集，dice是正常的，效果还可以。
2）如果训练集和测试集使用不同的数据集，dice一直为0
3）如果训练集使用数据A、B、C、D，测试集使用A、E，那么A的dice会有一定数值，但会保持一个定值，E的dice一直为0，如下图：
![image](https://user-images.githubusercontent.com/47233348/159441729-a1af0102-c2b0-4010-8240-7542c0fa8ea4.png)
问题二：
我是用您提供的ACDC的数据集，为什么avg会一直是一个定值，不会改变？
![image](https://user-images.githubusercontent.com/47233348/159442466-ef29af4b-27ac-48ab-b42e-d7d33be7f3ff.png)
非常期待您的回复，非常感谢！

**Comment by Dootmaan** [comment]
Hi @jscodecode, thank you for your valuable questions. 
For the first one, it would be best if you can also provide the training log because based on your current screenshot we cannot determine whether the training has gone right.
The second question leads us to a validation bug (thx again🙇‍) and it turns out that the previous version forget to turn the output into a binary mask before comparing with the label. It has been fixed in the latest commit and please clone our code again to run the experiment.

**Comment by Dootmaan** [comment]
*This issue is closed since no further activity has happened for a while.*

**Comment by cyc1111111111** [comment]
> 非常感谢你们很好的工作！但我有两个问题： 问题一：我使用的是冠脉数据集。 1）如果将同一组数据集既作为训练集，也作为测试集，dice是正常的，效果还可以。 2）如果训练集和测试集使用不同的数据集，dice一直为0 3）如果训练集使用数据A、B、C、D，测试集使用A、E，那么A的dice会有一定数值，但会保持一个定值，E的dice一直为0，如下图： 问题二： ![图像](https://user-images.githubusercontent.com/47233348/159441729-a1af0102-c2b0-4010-8240-7542c0fa8ea4.png) 我是用您提供的ACDC的数据集，为什么avg会一直是一个定值，不会改变？ ![图像](https://user-images.githubusercontent.com/47233348/159442466-ef29af4b-27ac-48ab-b42e-d7d33be7f3ff.png) 非常期待您的回复，非常感谢！

Hello, is your problem solved? I'm having the same issue as you，thank you for your reply
